Add folders for different git working options
icesi-devops/edu2020b-python pull request #17
Opened 2020-04-20 04:22 UTC by d4n13lbc

Add folders for different git working options

2020-04-21 04:57 UTC, d4n13lbc commented
Perhaps we will need to add some arrows to the vscode tutorial images

2020-04-24 02:29 UTC, LauraOrozco requested changes

2020-04-24 02:29 UTC, LauraOrozco commented on English/01_git/02_vscode/README.md
> +of fork, brach, and clone. We will also learn about a technology for creating slides that can be stored in github and viewed in any internet browser.
here the correct word is brach*,

2020-04-24 02:30 UTC, d4n13lbc commented on English/01_git/02_vscode/README.md
> +of fork, brach, and clone. We will also learn about a technology for creating slides that can be stored in github and viewed in any internet browser.
Thanks for the feedback

2020-04-24 02:36 UTC, LauraOrozco approved these changes

2020-04-24 02:36 UTC, merged